version: '3'
networks:
  net:
    driver: bridge

services:
  eshop:
    image: dancingfish/javaschool:eshop
    container_name: eshop
    restart: always
    ports:
      - 8081:8080
    expose:
      - 8081
    depends_on:
      - mysql
      - rabbitmq
      - flyway
    environment:
      db.url: jdbc:mysql://mysql:3306/eshopdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      rabbit.factory.hostname: rabbitmq
      hibernate.hbm2ddl.auto: update
    networks:
      - net

  eads:
    image: dancingfish/javaschool:eads
    container_name: eads
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - rabbitmq
      - eshop
      - flyway
      - mysql
    environment:
      spring.rabbitmq.host: rabbitmq
      spring.rabbitmq.port: 5672
      spring.rabbitmq.username: guest
      spring.rabbitmq.password: guest
    networks:
      - net


  rabbitmq:
    image: rabbitmq:3.5.3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    networks:
      - net

  flyway:
    container_name: flyway
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql -schemas=eshopdb -user=root -connectRetries=60 migrate
    volumes:
      - ./schema.sql:/flyway/sql/V1__Initial.sql
    depends_on:
      - mysql
    networks:
      - net

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: eshopdb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - net

volumes:
  db-data:
